export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_AlERT";
//REGISTER USER
export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
//LOGIN USER
export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
//Toggle side bar
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
//Logout user
export const LOGOUT_USER = "LOGOUT_USER";
//Update User
export const UPDATE_USER_BEGIN ="UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS ="UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR ="UPDATE_USER_ERROR";
